name: Feature request
description: Suggest an idea for this project.
title: 'Feature Request: [Title Here]'
labels: []
assignees: []
body:
  - type: textarea
    id: problem_description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: Describe the problem here
    validations:
      required: true
  - type: textarea
    id: solution_description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution here
    validations:
      required: true
  - type: textarea
    id: alternatives_description
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe alternatives here
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add additional context here
